AWSTemplateFormatVersion: 2010-09-09
Description: |
  backend resource infrastructure

Parameters:
  BackendStackName:
    Description: stackname for cleanup
    Type: String

Resources:

  instance:
    Type: "AWS::EC2::Instance"
    Properties:  
      ImageId: ami-0a634ae95e11c6f91
      InstanceType: t2.micro
      KeyName: testAwsCli
      SecurityGroups:
        - !Ref secGroup

  secGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Sec group for ec2 ssh access #required
  
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22 
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0

Outputs:
  publicIP:
    Value: !GetAtt instance.PublicIp
    Description: IP of created instance

  BackendStackName:
    Value: !Ref BackendStackName
    Export:
      Name: BackendStackName
